version: "2"
linters:
  enable:
    - govet
    - gocognit
    - gocyclo
    - maintidx
    - revive
    - wrapcheck
    - unparam
  settings:
    gocognit:
      min-complexity: 80
    gocyclo:
      min-complexity: 40
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
