// Proto/tonic stubs live in the `diag-proto` crate (../proto/rust),
// generated by `buf generate` using buf.build/community/neoeinstein-{prost,tonic}.
// Regenerate: cd ../proto && buf generate   (or `make generate` from the repo root)
pub use diag_proto::diagv1;

use crate::error::TldError;
use std::str::FromStr;
use tonic::{
    Request, Status,
    codegen::http::Uri,
    metadata::{Ascii, MetadataValue},
    service::interceptor::{InterceptedService, Interceptor},
    transport::Channel,
};

use diagv1::{
    device_service_client::DeviceServiceClient, org_service_client::OrgServiceClient,
    workspace_service_client::WorkspaceServiceClient,
};

pub type AuthedWorkspaceClient =
    WorkspaceServiceClient<InterceptedService<Channel, AuthInterceptor>>;

/// Normalises a server URL to include the `/api` suffix.
pub fn normalize_url(server_url: &str) -> String {
    let base = server_url.trim_end_matches('/');
    if base.ends_with("/api") {
        base.to_string()
    } else {
        format!("{base}/api")
    }
}

/// Build a gRPC channel to the given base URL.
pub async fn connect_channel(server_url: &str) -> Result<Channel, TldError> {
    let endpoint = if server_url.starts_with("http://") || server_url.starts_with("https://") {
        server_url.to_string()
    } else {
        format!("https://{server_url}")
    };
    let channel = Channel::from_shared(endpoint)
        .map_err(|e| TldError::Generic(e.to_string()))?
        .connect()
        .await?;
    Ok(channel)
}

#[derive(Clone)]
pub struct AuthInterceptor {
    token: MetadataValue<Ascii>,
}

impl Interceptor for AuthInterceptor {
    fn call(&mut self, mut request: Request<()>) -> Result<Request<()>, Status> {
        request
            .metadata_mut()
            .insert("authorization", self.token.clone());
        Ok(request)
    }
}

/// Creates a WorkspaceServiceClient with bearer-token authentication.
pub async fn new_workspace_client(
    server_url: &str,
    api_key: &str,
) -> Result<AuthedWorkspaceClient, TldError> {
    let channel = connect_channel(server_url).await?;
    let origin =
        Uri::try_from(normalize_url(server_url)).map_err(|e| TldError::Generic(e.to_string()))?;
    let token = MetadataValue::from_str(&format!("Bearer {api_key}"))
        .map_err(|e| TldError::Generic(e.to_string()))?;

    let interceptor = AuthInterceptor { token };
    let client =
        WorkspaceServiceClient::with_origin(InterceptedService::new(channel, interceptor), origin);
    Ok(client)
}

/// Creates a DeviceServiceClient for device-flow authentication.
pub async fn new_device_client(server_url: &str) -> Result<DeviceServiceClient<Channel>, TldError> {
    let channel = connect_channel(server_url).await?;
    let origin =
        Uri::try_from(normalize_url(server_url)).map_err(|e| TldError::Generic(e.to_string()))?;
    Ok(DeviceServiceClient::with_origin(channel, origin))
}

/// Creates an OrgServiceClient with bearer-token authentication.
pub async fn new_org_client(
    server_url: &str,
    api_key: &str,
) -> Result<OrgServiceClient<InterceptedService<Channel, AuthInterceptor>>, TldError> {
    let channel = connect_channel(server_url).await?;
    let origin =
        Uri::try_from(normalize_url(server_url)).map_err(|e| TldError::Generic(e.to_string()))?;
    let token = MetadataValue::from_str(&format!("Bearer {api_key}"))
        .map_err(|e| TldError::Generic(e.to_string()))?;

    let interceptor = AuthInterceptor { token };
    let client =
        OrgServiceClient::with_origin(InterceptedService::new(channel, interceptor), origin);
    Ok(client)
}

#[cfg(test)]
mod tests {
    use super::normalize_url;

    #[test]
    fn normalize_url_preserves_explicit_http_scheme() {
        assert_eq!(
            normalize_url("http://localhost:808"),
            "http://localhost:808/api"
        );
    }

    #[test]
    fn normalize_url_preserves_explicit_https_scheme() {
        assert_eq!(
            normalize_url("https://example.com"),
            "https://example.com/api"
        );
    }

    #[test]
    fn normalize_url_adds_api_to_scheme_less_urls() {
        assert_eq!(normalize_url("example.com"), "example.com/api");
    }
}
